server:
  port: 8071

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/niubiauthority?characterEncoding=utf8&useSSL=true
      username: root
      password: 123456
      initial-size: 5    #初始化时建立物理连接的个数,初始化发生在显示调用init方法，或者第一次getConnection时
      max-active: 100   #最大连接池数量
      min-idle: 2    #最小连接池数量
      max-wait: 60000  #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      connect-properties:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true

      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern:  /*

      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1